/**
 * Club crests bundled under public/logos, keyed by team id. The manifest is
 * generated by scripts/import-logos.mjs (see also scripts/fetch-logos.mjs).
 * Clubs without a file return null and callers fall back to the abbreviation
 * badge, so a missing crest can never break a screen.
 *
 * Every crest ships twice: WebP is what the browser downloads (~3.5KB vs 8.6KB
 * PNG), PNG stays as the <picture> fallback. The Matches feed can pull several
 * hundred crests at once, which is why the format matters.
 */
import manifest from "../data/logos.json";

const FILES = manifest as Record<string, string>;

export function crestSources(teamId: string): { png: string; webp: string } | null {
  const file = FILES[teamId];
  if (!file) return null;
  const base = `${import.meta.env.BASE_URL}logos/`;
  return { png: base + file, webp: base + file.replace(/\.png$/, ".webp") };
}
